### ISSUE TITLE
Long problem YAPIONSerializer

### ISSUE THREAD

**Issue by AstraDevNow** [yoyosource/YAPION#5]
Hello.
I have a problem with the YAPIONSerializer.
If I create a list in Java (List<String>) and add on this list a long inform of a string, serialize this then it is serialized as long and not as string.

**Comment by yoyosource** [comment]
Hello AstraDevNow,
thanks for reporting this Bug. I have found your bugs and fixed it. The next release will incorporate the required changes and the bug should be fixed then.

Regards YoyoSource
